apiVersion: v1
kind: PersistentVolume
metadata:
  name: nissim
  labels:
    app-name: nissim
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/nissim-pv