apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: random-number-hpa
  labels:
    app: random-number-hpa
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: random-number-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80    # target 80% memory usage
