apiVersion: v1
kind: Service
metadata:
  name: random-number-deployment
spec:
  selector:
    app: random-number-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
  